CREATE DATABASE posts;
CREATE SCHEMA public;
CREATE TABLE offers (
    id          BIGSERIAL NOT NULL PRIMARY KEY,
    item        TEXT NOT NULL,
    account     TEXT NOT NULL,
    nationality TEXT,
    description TEXT,
    price       MONEY NOT NULL,
    start_date  DATE,
    end_date    DATE,
    delivery    BOOLEAN NOT NULL,
    pickup      BOOLEAN NOT NULL,
    location    TEXT,
    ingredients TEXT[]
    );

insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'kwitling0', 'Guatemalan', 'sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque', 41.86, null, '12/18/2020', true, true, 'Smokvica');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ice Cream', 'rbrody1', 'Yaqui', null, 97.0, '11/3/2020', '11/18/2020', true, false, 'Phong Điền');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Water', 'evalder2', 'Pueblo', null, 60.61, '10/19/2020', '12/2/2020', true, true, 'Maoyang');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Sandwich', 'isibbe3', 'Cuban', 'id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien', 96.5, null, '12/9/2020', false, false, 'Třešť');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pho', 'rgary4', 'Micronesian', null, 36.97, '1/30/2020', '12/3/2020', false, true, 'Sokółka');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Jerk Chicken', 'aklimashevich5', null, null, 56.03, '8/22/2020', null, true, true, null);
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Sandwich', 'kfullilove6', 'Shoshone', 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse', 36.9, '1/9/2020', '12/1/2020', true, true, 'Mamburao');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Jerk Chicken', 'ltilsley7', 'Chickasaw', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 18.82, '4/17/2020', '12/24/2020', false, false, 'San Jose');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ice Cream', 'nbediss8', 'Peruvian', null, 6.29, '9/8/2020', null, true, true, null);
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Rice', 'dmcgiffin9', 'Colombian', 'a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis', 31.43, null, '12/16/2020', false, true, 'Ja Ela');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pasta', 'bbicea', 'Cambodian', 'placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', 72.45, null, '12/28/2020', false, false, 'Elekmonar');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ramen', 'pephgraveb', 'Tlingit-Haida', null, 46.63, null, '12/7/2020', true, true, 'Saint-Cloud');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Broccoli Soup', 'hadcockc', 'Puget Sound Salish', 'donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus', 66.87, null, '11/19/2020', false, false, 'Gumi');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pork Buns', 'tgoaned', 'Menominee', 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut', 65.52, '5/18/2020', '12/11/2020', false, true, 'Bununu Dass');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Water', 'prapporte', null, null, 24.64, '5/4/2020', '12/21/2020', true, true, 'Armenta');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pork Buns', 'hbalmadierf', null, null, 69.5, '1/29/2020', '12/3/2020', true, true, 'La Libertad');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ramen', 'eklawig', 'Shoshone', 'velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante', 31.18, null, null, false, true, null);
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Jerk Chicken', 'clevingsh', 'Micronesian', 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor', 48.04, null, '12/26/2020', true, false, 'Parthenay');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ramen', 'kpassyi', null, 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer', 98.96, '8/7/2020', '12/1/2020', true, false, 'Dolní Studénky');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'zclemesj', 'Shoshone', null, 38.99, '1/28/2020', '11/25/2020', false, true, 'Gunziying');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Sandwich', 'cjoshamk', 'Fijian', 'sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 18.59, null, '12/1/2020', true, true, 'Rumyantsevo');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Broccoli Soup', 'ccrichtonl', 'Venezuelan', 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat', 78.55, '2/9/2020', '12/28/2020', false, false, 'Krasnoye');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pasta', 'mdastm', 'Chinese', 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 32.05, null, '12/8/2020', false, false, 'Labuhankananga');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pasta', 'jlammingn', 'Asian', 'et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet', 88.5, null, '11/29/2020', false, true, 'Azteca');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Sandwich', 'sloghano', 'Chamorro', 'justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque', 71.75, null, '12/23/2020', false, false, 'Daejeon');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pasta', 'hmartynp', 'Delaware', null, 88.66, null, '12/18/2020', true, false, 'Carapelhos');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ice Cream', 'mrumensq', null, 'vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec', 53.14, '4/29/2020', '12/12/2020', false, true, 'Lahān');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ramen', 'ggregoriour', 'Delaware', 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis', 37.97, null, '11/24/2020', false, false, 'Souq Larb’a al Gharb');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Rice', 'wpinors', null, null, 77.73, '7/22/2020', '12/19/2020', true, true, 'Yên Lạc');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pho', 'agaythwaitet', 'Native Hawaiian', null, 21.34, '7/23/2020', '11/28/2020', false, false, 'Aikmel');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Jerk Chicken', 'amatousu', null, 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam', 93.22, '7/8/2020', null, true, false, null);
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Water', 'strickettv', 'Uruguayan', 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', 57.97, null, '12/6/2020', false, false, 'Puerto Rico');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Jerk Chicken', 'bmacneelyw', 'Tongan', null, 73.11, '9/25/2020', '12/23/2020', false, true, 'Longshan');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Water', 'dexrollx', 'Crow', 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', 44.51, '10/4/2020', '12/15/2020', true, false, 'Wucheng');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ice Cream', 'kmainstoney', 'Cambodian', 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 71.05, null, '11/25/2020', false, true, 'Sabang');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pork Buns', 'ebeynkez', 'Bangladeshi', 'accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 48.58, '5/1/2020', '11/28/2020', false, true, 'Nankai');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pasta', 'rsmythin10', 'Latin American Indian', null, 93.4, '3/29/2020', '11/14/2020', true, false, 'Phlapphla Chai');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pho', 'dlevett11', 'Ute', 'rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis', 19.37, '6/30/2020', '11/27/2020', false, false, 'Bezhta');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pho', 'wscotchmer12', 'Taiwanese', 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed', 51.23, '11/26/2019', '11/13/2020', true, true, 'Évosmos');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ramen', 'pstanbra13', 'Ecuadorian', null, 80.14, '10/26/2020', '12/23/2020', false, true, 'Liliba');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Broccoli Soup', 'lingree14', 'Asian Indian', 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis', 39.38, '11/29/2019', '12/9/2020', true, false, 'Panzhou');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ice Cream', 'amelbourn15', 'Creek', 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus', 54.24, '6/5/2020', '12/14/2020', false, false, 'Yuanbao');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ice Cream', 'bbenedidick16', 'Blackfeet', null, 87.81, '7/12/2020', '12/11/2020', false, false, 'Wielki Kack');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'kwoolsey17', 'Apache', 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed', 59.68, '7/22/2020', '12/2/2020', true, true, 'Kaltungo');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pork Buns', 'lshildrick18', null, null, 20.38, null, null, false, false, null);
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Jerk Chicken', 'mdearell19', null, null, 92.04, '9/10/2020', '12/13/2020', false, false, 'Presidente Médici');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pork Buns', 'ehoundesome1a', null, null, 5.13, '8/16/2020', '11/15/2020', true, true, 'San José');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Broccoli Soup', 'eblay1b', 'Alaskan Athabascan', null, 79.96, '8/30/2020', '12/28/2020', true, true, 'Sioux Falls');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Rice', 'awilse1c', 'Micronesian', null, 41.43, '5/20/2020', '12/22/2020', false, true, 'Bristol');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'mhollow1d', 'Lumbee', 'dolor morbi vel lectus in quam fringilla rhoncus mauris enim', 17.27, '5/18/2020', '11/13/2020', true, true, 'Chaoshui');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'sgremain1e', 'Apache', null, 65.23, null, '12/2/2020', true, true, 'Sychëvo');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ramen', 'fgoolden1f', null, null, 80.82, '9/4/2020', '12/7/2020', false, true, 'Stroitel’');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Broccoli Soup', 'kabramsky1g', 'Native Hawaiian', 'cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet', 77.83, '1/8/2020', '12/6/2020', true, true, 'Nageswari');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Water', 'drawlingson1h', null, 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', 37.0, null, '12/6/2020', true, false, 'Filabusi');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pork Buns', 'rmcgilbon1i', 'Chinese', null, 80.25, '6/16/2020', '12/20/2020', true, false, 'Velikiye Borki');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ramen', 'amuzzullo1j', 'Salvadoran', 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor', 85.11, '4/19/2020', '12/29/2020', false, true, 'Kadudampit');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Broccoli Soup', 'lscotchbourouge1k', 'Cherokee', 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse', 17.32, '7/3/2020', '12/13/2020', false, true, 'Perpignan');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Broccoli Soup', 'anegri1l', 'Cuban', null, 27.59, '11/18/2019', '12/18/2020', false, false, 'Machov');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'ctrembey1m', 'Alaska Native', 'quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus', 42.0, null, '11/29/2020', false, true, 'Pajung');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pasta', 'ajeanon1n', 'Sioux', null, 59.61, '7/25/2020', '12/16/2020', true, true, 'Hedao');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Rice', 'dielden1o', null, 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum', 42.22, '2/16/2020', null, true, true, null);
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'rciobutaro1p', 'Korean', null, 56.04, '6/24/2020', '12/8/2020', false, false, 'Amagi');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'gstanfield1q', null, null, 62.65, null, '12/14/2020', false, false, 'Lecheng');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ice Cream', 'ddundredge1r', null, 'nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas', 21.02, null, null, false, false, null);
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'aaulds1s', null, 'in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor', 14.2, '8/23/2020', '12/16/2020', false, false, 'Šilheřovice');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Sandwich', 'tcaldero1t', null, null, 86.37, '8/29/2020', '12/10/2020', false, false, 'Fontvieille');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Jerk Chicken', 'dlongthorn1u', null, 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', 88.85, '4/21/2020', '12/1/2020', true, false, 'Ban Talat Bueng');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Rice', 'tcaesmans1v', 'Shoshone', null, 97.87, '2/4/2020', '12/28/2020', true, true, 'Manta');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Broccoli Soup', 'jhazelden1w', 'Sioux', 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo', 63.95, '4/1/2020', '11/17/2020', true, true, 'Luzon');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Rice', 'ccuerdale1x', 'Ecuadorian', null, 96.3, null, '12/20/2020', false, true, 'Kawangohari');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pho', 'gborles1y', null, null, 67.36, null, '11/22/2020', false, false, 'Sinjai');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Water', 'rseekings1z', 'Guatemalan', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', 29.52, '8/6/2020', '12/19/2020', false, false, 'Smiltene');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ramen', 'akabisch20', 'Crow', 'congue diam id ornare imperdiet sapien urna pretium nisl ut', 14.85, null, '11/28/2020', false, true, 'Cibulakan');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'esimonich21', 'Pueblo', null, 57.07, null, '11/25/2020', true, false, 'Sambungjaya');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ice Cream', 'wfotherby22', 'Yuman', 'quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', 88.77, '12/29/2019', '11/19/2020', true, true, 'Dadoupu');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'tchichgar23', 'Pima', null, 67.14, '8/18/2020', '12/6/2020', true, false, 'Putrajaya');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Rice', 'kpullan24', 'Aleut', null, 29.51, null, '12/3/2020', false, false, 'Blimbing');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pasta', 'showick25', 'Alaska Native', 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis', 57.58, '11/27/2019', '12/27/2020', false, true, 'Uničov');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pasta', 'rmctrusty26', 'Comanche', null, 77.83, '5/18/2020', '12/30/2020', false, false, 'Purranque');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Water', 'rprop27', null, null, 31.34, null, '12/21/2020', false, false, 'Tomorlog');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Water', 'csambells28', 'Bangladeshi', null, 65.86, null, '11/15/2020', true, false, 'Madrid');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pasta', 'kkench29', 'American Indian and Alaska Native (AIAN)', null, 30.76, null, '11/16/2020', true, true, 'Katrineholm');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Water', 'gwasiela2a', 'Venezuelan', null, 42.21, null, '12/16/2020', true, false, 'Ciwaru');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pork Buns', 'kbertram2b', 'Cambodian', null, 17.24, '5/15/2020', '12/25/2020', false, false, 'Parchal');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Water', 'gleat2c', null, 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit', 41.84, '7/3/2020', '12/8/2020', true, true, 'Namysłów');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ramen', 'blaverack2d', 'Ottawa', null, 87.25, '9/15/2020', '12/22/2020', false, false, 'Nizhniy Novgorod');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Rice', 'ccrecy2e', 'Argentinian', null, 17.67, null, null, true, true, null);
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Sandwich', 'adeane2f', 'Spaniard', null, 40.22, null, '12/7/2020', false, false, 'Skanör');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Rice', 'aevesque2g', null, null, 79.36, null, '11/22/2020', false, true, 'Phra Nakhon Si Ayutthaya');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pasta', 'fhurkett2h', 'Tohono O''Odham', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla', 29.79, null, '12/29/2020', false, false, 'Al Mughayyir');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pork Buns', 'bhancill2i', 'Micronesian', null, 54.18, '5/27/2020', '12/4/2020', true, true, 'Hà Tĩnh');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ice Cream', 'jbichard2j', 'Peruvian', 'eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse', 36.27, null, '12/20/2020', true, true, 'Ciawi');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Rice', 'glofthouse2k', 'Pakistani', 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', 89.75, '11/4/2020', '11/13/2020', true, false, 'Bunut');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ramen', 'amessruther2l', null, 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis', 57.86, null, null, true, false, null);
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Ice Cream', 'ccotgrove2m', 'Colville', 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id', 49.86, '11/25/2019', '12/19/2020', true, false, 'Buga');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pho', 'drawles2n', 'Alaska Native', null, 80.8, '2/19/2020', '11/29/2020', true, false, 'Dal’nerechensk');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Pork Buns', 'ileyman2o', 'Potawatomi', null, 79.84, null, '12/23/2020', true, false, 'Poniatowa');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Fried Chicken', 'eredford2p', 'Asian Indian', null, 77.58, '7/2/2020', '12/4/2020', true, true, 'Ansongo');
insert into offers (item, account, nationality, description, price, start_date, end_date, delivery, pickup, location) values ('Jerk Chicken', 'lfilintsev2q', null, 'faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend', 87.08, null, '12/26/2020', false, false, 'Xiaxihao');
